# Generated by Django 5.2.6 on 2025-09-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('resumen', models.CharField(max_length=300, verbose_name='Resumen')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('palabras_clave', models.CharField(max_length=200, verbose_name='Palabras clave')),
                ('imagen_url', models.URLField(max_length=500, verbose_name='Link de la Imagen')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
